### ISSUE TITLE
Scorer Revamp Feedback Ticket

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/passport#1008]
#### Todo items that need to be adjusted / corrected:

- [x] Creation date of Scorer is not correct (showing 1969)
- [x] Always order by Scorer ID (not most recently changed... to confirm, edit a scorer name and confirm it stays in the same list location)
- [x] Increase border weight to 2px on scorer selection
- [x] Change font color on "sample Applications" and "Quick Links" to grey/500 (see Figma) - we are trying to make sure these stand out as a heading
- [ ]

**Comment by Etovardesign** [comment]
Global changes / updates to be made:
- [ ] All of the copy in the UI should have a line height of 150%.
- [ ] Top header bar
      - [ ] Figma component [desktop-header](https://www.figma.com/file/FVJyu48WmSKWXOCKhZioCw/Scorer-UI-Library-(WIP)?node-id=3%3A501&t=gaSTWVic9gJlAsHc-1)
      - [ ] Height should be 64p
      - [ ] Update vertical rhythm to match Figma designs
- [ ] Update Scorer UI grid system to match Desktop & Mobile responsive designs [Desktop & Mobile Grids](https://www.figma.com/file/FVJyu48WmSKWXOCKhZioCw/Passport-UI-Library-(WIP)?node-id=3%3A199&t=TypVqW1gffxpeTzq-1)

**Comment by Etovardesign** [comment]
**Left-side panels**
- [ ] Figma designs [scorer-right-side-panels](https://www.figma.com/file/FVJyu48WmSKWXOCKhZioCw/Passport-UI-Library-(WIP)?node-id=70%3A1585&t=gaSTWVic9gJlAsHc-1)

- "Quick Links" should be in 12p font size, color: grey-500.
- Corner radiuses should be 4p.
- Panel outline should be 1p, inside, color: 'grey-100'.
- Vertical rhythm should match the Figma design.

**Comment by Etovardesign** [comment]
**'Select Use Case' pop-up**
Figma designs (pop-up & cards)
[vertical-rhythm-scorer-usecase](https://www.figma.com/file/FVJyu48WmSKWXOCKhZioCw/Scorer-UI-Library-(WIP)?node-id=66%3A1158&t=gaSTWVic9gJlAsHc-1)

[scorer-card-usecase](https://www.figma.com/file/FVJyu48WmSKWXOCKhZioCw/Passport-UI-Library-(WIP)?node-id=76%3A2131&t=gaSTWVic9gJlAsHc-1)

- [ ] Card descriptor copy should be 12p (150% line spacing)
- [ ] Vertical rhythm should match Figma designs

**Comment by Etovardesign** [comment]
**Select a Scorer**
Cards (default & selected)
[scorer-card-scorer_type](https://www.figma.com/file/FVJyu48WmSKWXOCKhZioCw/Passport-UI-Library-(WIP)?node-id=6%3A341&t=gaSTWVic9gJlAsHc-1)

- Outline should be 2p, color: violet-400 (selected)
- Update the vertical rhythm to match the Figma designs

**Comment by Etovardesign** [comment]
**Homepage Scorer Created**
Full Page
[vertical-rhythm-scorer-created](https://www.figma.com/file/FVJyu48WmSKWXOCKhZioCw/Passport-UI-Library-(WIP)?node-id=67%3A1350&t=gaSTWVic9gJlAsHc-1)

Tabs
[scorer-left-side-tabs](https://www.figma.com/file/FVJyu48WmSKWXOCKhZioCw/Passport-UI-Library-(WIP)?node-id=4%3A1007&t=gaSTWVic9gJlAsHc-1)

- Update corner radius to 4p
- Alignment should be vertically centered
- Update vertical rhythm to match Figma designs

**Comment by Kweiss** [comment]
- [] The created at date seems to be missing now on the scorers. Lets add in the correct date.

**Comment by lucianHymer** [comment]
@Kweiss The date should be shown for any new scorers, but we weren't storing the created_at date before

**Comment by lucianHymer** [comment]
Ready for review on the review server!
