### ISSUE TITLE
Enable First-in-First-out deduplication mechanism

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1027]
Currently, the Gitcoin Passport API only supports Last-in-First-out (LIFO) deduplication strategy for preventing duplicate stamps from skewing the verification process. However, some developers may prefer an alternative deduplication mechanism such as First-in-First-out (FIFO).

**Acceptance Criteria**

GIVEN an API user has created a new Gitcoin Scorer instance and selected FIFO as the deduplication mechanism from the available options
WHEN the Gitcoin Scorer instance is initialized and starts receiving verifiable credentials (VCs) from Gitcoin Passports
THEN the Gitcoin Scorer instance must implement the FIFO deduplication method

GIVEN a FIFO scorer of the Passport API is used for verification of Passports
AND a Passport holder submits a verifiable credential stamp to the scorer that has already been submitted by another Passport holder
WHEN the duplicate stamp is detected
THEN the Passport API must exclude the weight of that stamp from the previous Passport score calculations that included it and recalculate the score accordingly
AND the duplicate stamp must be accounted into the score of the Passport that submitted it last

**Tasks:**

- [ ] Add a new configuration option to allow developers to choose the deduplication method
- [ ] Implement the FIFO deduplication method
- [ ] Test the new deduplication method with sample data to ensure accuracy

**Comment by schultztimothy** [comment]
Should we make the signature required for fifo? Without verification couldn't a malicious user submit stamps they do not own in order to hurt the scores of other users?

**Comment by schultztimothy** [comment]
Here are steps to test this

1. Go to https://review.passport.gitcoin.co/#/dashboard and create the same stamp `i.e.  Github` for multiple accounts.
2. Create a community and select the fifo deduplication method
3. Go to https://api.review.scorer.gitcoin.co/docs and submit first passport ![Image](https://user-images.githubusercontent.com/6887938/227981113-f2cd3103-6270-46ac-aef4-37af4ce3dd65.png)
4. Verify that stamps were created from django admin https://api.review.scorer.gitcoin.co/admin/ and that a score was created(may take a little time)
5. Submit the second account here: ![Image](https://user-images.githubusercontent.com/6887938/227981113-f2cd3103-6270-46ac-aef4-37af4ce3dd65.png) 
6. Verify that the stamps for the first account were deleted, second account has the expected stamps, and the scores were updated for both accounts
