### ISSUE TITLE
Exploration of On-Chain Gitcoin Passport Stamps Technical Implementation

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1031]
_As part of our efforts to improve the functionality, security, and trust of blockchain apps and increase their adoption by users, we want to explore the technical implementation of Ethereum Attestation Service-based stamps in Gitcoin Passport. The purpose of this spike is to understand how to implement Ethereum Attestation Service-based stamps for issuing Gitcoin Passport stamps on-chain._

**Background:**

The problem that Gitcoin Passport scoring on-chain aims to solve is the inability for blockchain app developers to verify the unique humanity and other attributes of their participants using identity data that is natively composable with their smart contracts. This limitation prevents the creation of secure and trustworthy applications, limiting the functionality and capabilities of blockchain apps. The proposed solution is Gitcoin Passport scoring on-chain, a digital identity solution that allows developers to verify the unique humanity and attributes of their participants while preserving privacy, coercion- and censorship resistance, and correct execution of the policies around identity.

**Goals:**

The goal of this spike is to scope a minimum viable technical implementation that aims to address the customer problem by allowing Passport holders to claim an Ethereum Attestation Service-based Gitcoin Passport stamp on-chain. The first iteration of the Passport scoring on-chain should focus on issuing stamps on-chain, and integrating the issuance of stamps with the existing Passport holder experience.

**Tasks:**

- [x] Research and understand the technical implementation of Ethereum Attestation Service-based stamps for issuing Gitcoin Passport stamps on-chain.
- [x] Document findings and present them in a report.
- [x] Define the technical requirements for integrating the issuance of stamps with the existing Passport holder experience.

**Links:**

- Ethereum Attestation Service: https://attest.sh/

**Comment by nutrina** [comment]
Have created a small project to test the EAS functionality: https://github.com/nutrina/test_eas
Currently waiting for rasponse from EAS regarding errors I get when testing the delegated attestation.

**Comment by nutrina** [comment]
The current status & the findings have been documented in Notion, in the "Passport Technical Documentation" document.
