### ISSUE TITLE
Build a Dashboard to Track Gitcoin Scorer API Calls per API Key

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1043]
Build a dashboard or another method to track the number of API calls per API key in the Gitcoin Scorer API. The dashboard or tool should allow us to monitor usage of the API and ensure that each API key is being used appropriately and within the set limits.

**Acceptance Criteria:**

- The dashboard or tool tracks the number of API calls per API key.
- The dashboard or tool displays the usage of each API key in real-time or near-real-time.

**Tasks:**

- [x] Evaluate the existing Gitcoin Scorer API codebase and identify areas that require modification to implement API usage tracking.
- [x] Implement the necessary changes to the Gitcoin Scorer API codebase to enable usage tracking.
- [x] Develop a dashboard or tool to monitor API key usage and provide usage data in real-time or near-real-time.

**Comment by schultztimothy** [comment]
I created a new model that will track api key usage across the public registry API key. Given we go with the jupyter notebook style of data analysis this could be a possible output for viewing api key usage. Also could be further customized/analyzed


![Image](https://user-images.githubusercontent.com/6887938/228695220-f17175e2-ad9c-4134-b71b-66952d3d37e9.png)

**Comment by schultztimothy** [comment]
After talking with @nutrina today he suggested updating how api calls are tracked to include a timestamp for each request so that requests over time can be tracked. Updating this today.

**Comment by schultztimothy** [comment]
Waiting for CSV and  infrastructure improvements moving this to blocked until those are ready

**Comment by nutrina** [comment]
I am unblocking this, as the evaluation (dashboard) for the required metrics will be created by the data team.
