### ISSUE TITLE
Identify the Best Approach for Bringing a Bulk of Stamps On-Chain with Ethereum Attestation Service (EAS) Proxy Contract

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1072]
We are working on a feature to allow Gitcoin Passport holders to bring their stamps on-chain and update their on-chain Passport copies. One of the potential solutions is to use a Proxy Contract with the Ethereum Attestation Service (EAS) to handle the bulk transfer of stamps. Before proceeding with implementation, we need to investigate the feasibility, efficiency, and potential limitations of this approach.

### Goal:
Determine the viability and optimal method for using a Proxy Contract with the Ethereum Attestation Service (EAS) to bring a bulk of stamps on-chain.

### Tasks:

- [x] Review the Ethereum Attestation Service (EAS) documentation and relevant codebase to understand how Proxy Contracts work in this context.
- [x] Investigate the technical requirements and constraints for implementing a Proxy Contract for the bulk transfer of stamps on-chain.
- [ ] Assess the potential gas costs and efficiency of using a Proxy Contract for this purpose.
- [ ] Evaluate any security concerns or risks associated with using a Proxy Contract for handling the on-chain transfer of stamps.
- [ ] Identify any alternative approaches or optimizations that could improve the efficiency, security, or simplicity of the solution.
- [ ] Document your findings and recommendations for the best approach to bring a bulk of stamps on-chain using the Ethereum Attestation Service (EAS) Proxy Contract.

### Acceptance Criteria:

- A comprehensive analysis of the feasibility, efficiency, and potential limitations of using a Proxy Contract with the Ethereum Attestation Service (EAS) to bring a bulk of stamps on-chain.
- A clear recommendation for the best approach to implement this feature, along with any identified alternatives or optimizations.
- Detailed documentation of findings to help inform the development team's decision-making process.

**Comment by nutrina** [comment]
Progress:
- [] write multiple attestations to EAS from Proxy Contract
- [] validate the attestations, by verifying signature
    - [] the signature would be provided by IAM server
    - [] signature could be an EIP712 signature, for the array of attestations being written
    - [] should contain a unique nonce. The Nonce could be incremental, starting from 0 for attestation receiver (similar like in the delegated attestations in the EAS contracts)

**Comment by schultztimothy** [comment]
I'm wondering if we might want to have the iAM server issue a new, eip712 signed, credential that is a summary of all of the credentials a passport currently owns. Instead of the credentialSubject being a single provider it could be an array or providers like 
```
"credentialSubject": {
    "id": "did:pkh:eip155:1:0x12FeD9f987bc340c6bE43fD80aD641E8cD740682",
    "providers": ["Twitter", "Facebook", "Google"],
    "hash": "v0.0.0:AjcRjxx7Hp3PKPSNwPeBJjR21pLyA14CVeQ1XijzxUc="
  },
```

The proxy smart contract could then just verify one credential and proof. If the proof is valid it can then loop over all of the providers and make individual attestation calls to the EAS contract for each provider like https://github.com/gitcoinco/eas-proxy/blob/main/contracts/GitcoinAttester.sol

I had this repo going from when we were looking into this previously but wasn't able to get it to validate yet  https://github.com/schultztimothy/passport-vc-verification/compare/accept-array-of-providers?expand=1 

Happy to dig into it more on Monday but just wanted to send it out if you guys wanted to take a look

**Comment by nutrina** [comment]
Closing this Ticket for now, as we have sufficient information for how to bring stamps on-chain as EAS attestations.
