### ISSUE TITLE
Ensure Accurate Reflection of On-Chain Stamp Status in the User Interface (v0)

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1073]
We are developing a feature to enable Gitcoin Passport holders to bring their stamps on-chain and update their on-chain Passport copies. One of the user stories requires us to display the on-chain status of individual stamps in the user interface. For version 0, we will not consider the timestamps or expiry of on-chain stamps. To ensure the accuracy and consistency of on-chain status display, we need to investigate the best approach to retrieve and present this information in the user interface.

### Goal:
Determine the optimal method for accurately reflecting the on-chain status of stamps in the user interface, without considering timestamps or expiry in v0.

### Tasks:

- [x] Review the current implementation of the Gitcoin Passport user interface and identify the components that will display on-chain status.
- [x] Investigate the available methods for querying on-chain stamp status from the Ethereum Attestation Service (EAS) or other relevant sources.
- [x] Evaluate the performance, efficiency, and limitations of each method for retrieving on-chain stamp status.
- [x] Assess the potential impact on user experience, such as load times or responsiveness, when incorporating on-chain stamp status retrieval into the user interface.
- [x] Identify any alternative approaches or optimizations that could improve the accuracy, efficiency, or user experience of displaying on-chain stamp status in the user interface.
- [x] Document your findings and recommendations for the best approach to ensure accurate reflection of on-chain stamp status in the user interface.

### Acceptance Criteria:

- A comprehensive analysis of the available methods for retrieving and displaying on-chain stamp status in the user interface.
- A clear recommendation for the best approach to implement this feature, along with any identified alternatives or optimizations.
- Detailed documentation of findings to help inform the development team's decision-making process.

**Comment by nutrina** [comment]
@michaelgreen06 let's chat about this after standup.
I would move on with this, and use the EAS indexer ( https://sepolia.easscan.org/graphql ), it seems the most obvious choice.
@chibie has picked up the follow-up task #1087

**Comment by michaelgreen06** [comment]
**A comprehensive analysis of the available methods for retrieving and displaying on-chain stamp status in the user interface.**
- (option 1) one icon next to the verified badge 
	- If stamp was stored on multiple networks clicking this would show all networks where stamp is stored
		- Clicking on the network would open a new tab that shows its location on chain
	- "bring on chain" button would have a dropdown to select which network you want to write stamps to
	- component = platformcard
- (option 2) Progress bar at the top of the page showing how many stamps are claimed on each network 
	- Clicking the progress bar provides the option to bring stamps on chain or view stamps on that network
		- you can select which stamps you want to put on that network
	- Component =new header
- (option 3) Advanced view button
	- clicking this button enables the "bring stamps on chain" button and a network selector
		- Selecting a specific network shows which stamps are on that network
			- They would appear w/ current Verified button & badge
		- Clicking the "bring stamps on chain" button opens a menu that allows you to select which stamps you want to bring on that network
	- Component = Header
- (option 4) Icon for each network in the upper right portion of the stamp
	- Could also have a filter option that would allow users to show stamps only from certain networks
	- icon component=platformcard
	- filter option component=header

**Evaluate the performance, efficiency, and limitations of each method for retrieving on-chain stamp status.**
- (option 1) EAS GraphQL End point
	- This is already built and it can handle our current traffic load
	- It is scaleable - if our traffic exceeds the rate limits from EAS we can easily fork the indexer & run our own 
		- There is also an endpoint for every network that EAS is operating on
	- https://sepolia.easscan.org/graphql
- (option 2) The Graph
	- we'd basically be duplicating the work EAS has already done w/ their apollo server 
	- It is decentralized, which means it is more resistant to censorship but it is also slower
		- We'd experience similar delays as seen w/ GTC staking
- (option 3) Build our own indexer using Mo's Chainsauce
	- We would control everything but we'd also need to maintain it
	- Would be a decent amount of work to build the indexer this way. 
		- If we want to build our own indexer we should just for the EAS one
	- https://github.com/gitcoinco/allo-indexer,

**A clear recommendation for the best approach to implement this feature, along with any identified alternatives or optimizations.**
- We should proceed with using the EAS GraphQL endpoint (option 1) to retrieve the on chain status of stamps.
	- This approach is likely the least amount of work and is also the most robust and scaleable. It also is likely to have quick response times that minimize the chances for bad UX
- We should display the on chain status as an icon next to the current verified badge on the platformcard component (option 1)
	- This should be easy to implement, should be scaleable for multiple networks & shouldn't negatively impact or complicate the user experience

**Comment by nutrina** [comment]
> **A comprehensive analysis of the available methods for retrieving and displaying on-chain stamp status in the user interface.**
> 
> * (option 1) one icon next to the verified badge
>   
>   * If stamp was stored on multiple networks clicking this would show all networks where stamp is stored
>     
>     * Clicking on the network would open a new tab that shows the stamp's location on chain
>   * "bring on chain" button would have a dropdown to select which network you want to write stamps to
>   * component = platformcard
> * (option 2) Progress bar at the top of the page showing how many stamps are claimed on each network
>   
>   * Clicking the progress bar provides the option to bring stamps on chain or view stamps on that network
>     
>     * you can select which stamps you want to put on that network
>   * Component =new header
> * (option 3) Advanced view button
>   
>   * clicking this button enables the "bring stamps on chain" button and a network selector
>     
>     * Selecting a specific network shows which stamps are on that network
>       
>       * They would appear w/ current Verified button & badge
>     * Clicking the "bring stamps on chain" button opens a menu that allows you to select which stamps you want to bring on that network
>   * Component = Header
> * (option 4) Icon for each network in the upper right portion of the stamp
>   
>   * Could also have a filter option that would allow users to show stamps only from certain networks
>   * icon component=platformcard
>   * filter option component=header
> 
> **Evaluate the performance, efficiency, and limitations of each method for retrieving on-chain stamp status.**
> 
> * (option 1) EAS GraphQL End point
>   
>   * This is already built and it can handle our current traffic load
>   * It is scaleable - if our traffic exceeds the rate limits defined by EAS, we can easily fork [their indexer](https://github.com/ethereum-attestation-service/eas-indexing-service) & run our own
>     
>     * There is also an endpoint for every network that EAS is operating on - easy to apply this approach to other networks
>   * https://sepolia.easscan.org/graphql
> * (option 2) The Graph
>   
>   * we'd basically be duplicating the work EAS has already done w/ their graphQL endpoint
>   * It is decentralized, which means it is more resistant to censorship but it is also slower
>     
>     * We'd experience similar delays as seen w/ GTC staking
> * (option 3) Build our own indexer using Mo's Chainsauce
>   
>   * We would control everything but we'd also need to maintain it
>   * Would be a decent amount of work to build the indexer this way.
>     
>     * If we want to build our own indexer we should just fork the EAS one
>   * https://github.com/gitcoinco/allo-indexer,
> 
> **A clear recommendation for the best approach to implement this feature, along with any identified alternatives or optimizations.**
> 
> * We should proceed with using the EAS GraphQL endpoint (option 1) to retrieve the on chain status of stamps.
>   
>   * This approach is likely the least amount of work and is also the most robust and scaleable. It also is likely to have quick response times that minimize the chances for bad UX
> * We should display the on chain status as an icon next to the current verified badge on the platformcard component (option 1)
>   
>   * This should be easy to implement, should be scaleable for multiple networks & shouldn't negatively impact or complicate the user experience

Nice job :)
