### ISSUE TITLE
Ceramic ComposeDB node upgrade

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1249]
### User Story:
As a member of Passport work stream
We want to upgrade our Ceramic node to ComposeDb
So that we can have indexing and a more stable decentralized environment committed to our Open Data principles

### Acceptance Criteria
GIVEN a user of Passport connects
WHEN a user updates their passport (add or remove a credential)
THEN the full passport data is written to our Ceramic node running ComposeDB 

#### Tasks:

- [ ] Spin up the ComposeDB node - this is relatively easy as @kammerdiener will be able to create
- [ ] Update Passport schema (really close, blocked on OP, they may have aligned on EAS standard today)
- [ ] New schema agreed
- [ ] EIP712 signature embedded into the VC (it would match to EAS)
Front end (really quick, update to the new Schema)
- [ ] Look at new node 
- [ ] Write to the new schema
- [ ] IAM server would need to issue the new format VCs to be written 
- [ ] Update the docs the know the GraphQL interface is available

#### Tech Details:
[Passport Schema Update(s)](https://docs.google.com/document/d/1lRM1MaiWwuwp8ZDknrJgHvk9OJn1wAa8Fj6Wymj1Dws/edit)

#### Open Questions:

- [ ] Can we re-load all of the data from our previous ceramic node into Compose DB? (is this something Ceramic could do for us?)
- [ ] 

#### Notes/Assumptions:
The Snapshot SDK migration has completed (in progress with Sophia and Zakk)

**Comment by schultztimothy** [comment]
Heres an example using didkit, to issue VCs with an EIP712 signature https://github.com/schultztimothy/passport-vc-verification/blob/main/utils/sign.ts#L22. Didkit does not provide much documentation for this signature type

**Comment by nutrina** [comment]
This is a gist that issues VCs in the new format with the new signature: https://gist.github.com/nutrina/9306e82080d34abc33aa696753c6c4f2

**Comment by Jeremy-Gitcoin** [comment]
Need to create additional issues for all of the work needed to complete

**Comment by nutrina** [comment]
Have updated gist to account for the latest changes (includes the `customInfo` now): https://gist.github.com/nutrina/9306e82080d34abc33aa696753c6c4f2

**Comment by nutrina** [comment]
I would propose the following plan to get this implemented and released:

### Release step 1 - roll out the tech in the backend services
This should be pushed to prod before the actual go-live.
This sill roll out the required tech on our backend services.

- [ ] Updates to IAM: https://github.com/gitcoinco/passport/issues/1540
- [ ] Updates to Scorer: https://github.com/gitcoinco/passport/issues/1541
- [ ] Updates to Scorer - remove backfilling data from Ceramic: https://github.com/gitcoinco/passport/issues/1543

###  Release Step 2 - go live
This should be preferably be performed in a period of relatively low traffic (no new events launching that week).
This will result in a higher load in our service due to the on-the-fly conversion of stamps when reading from the Passport App. This means before rolling this out we should ensure higher compute power on our end. This should gradually go down, while old stamps will expires, and should be back to normal after 90 days.

- [ ] Support for reading & writing to / from Compose in the new schema format: https://github.com/gitcoinco/passport/issues/1545
- [ ] Drop back-filling from ceramic: https://github.com/gitcoinco/passport/issues/1544
- [ ] Update the Passport App: https://github.com/gitcoinco/passport/issues/1542


### Step 3 (post go-live cleanup)
Should be performed when we are confident that it is not relevant for the user any more to have the on-the-fly ocnversion of the stamps in place (for example after 90 days all old stamps of the users should be expired, so this should be safe to do):
- [ ] Drop the on-the-fly conversion in the scorers ceramic-cache API: https://github.com/gitcoinco/passport-scorer/issues/333
