### ISSUE TITLE
Gas Optimization for Passport Smart Contract

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1252]
This depends on #1250 and #1251 

Our aim is to optimize gas usage in the Passport Smart Contract based on the recommendations by EAS. This will ensure the efficient operation of our smart contract.

Please make sure to check out this updated POC from EAS: https://github.com/slavik0329/test_eas/tree/delegate-proxy

### Tasks

- [ ] **Remove Redundant Loop:** Remove the redundant loop in the smart contract and utilise the multiAttest function in EAS for efficiency and gas optimisation.
- [ ] **Comment Out console.sol:** Comment out the console.sol library if it's not being used, to save gas and avoid unnecessary operations.
- [ ] **Optimize Data Fields:**
  - [ ] Convert many of the string data fields to smaller data types. For instance, convert date strings to uint and hashes to bytes32. This will save significantly on gas.
  - [ ] Consider creating a separate schema for registering providers and then referencing their UID in a bytes32 `providerId` instead of using a string. This can also lead to substantial gas savings.
- [ ] remove redundancies in payloads: `provider` and `stampHash` are redundant if they are included in the encodedData:
```ts
provider: googleStamp.provider,
stampHash: googleStamp.stampHash,
expirationDate: googleStamp.expirationDate,
encodedData: easEncodeData(googleStamp),
```

**Comment by nutrina** [comment]
Have deployed a new schema to Sepolia: 0xd83994d5459162a259c3a18d3db267ca05982f1e1e261d5388a8bfe2a2a2c7f9
https://sepolia.easscan.org/schema/view/0xd83994d5459162a259c3a18d3db267ca05982f1e1e261d5388a8bfe2a2a2c7f9

The plan is to:
- [ ] hash the provider and only store the byte32 hash 
- [ ] write the raw hash from the VC (the hash is a sha256, hence the byte32 field for that). We'll get back the sha256 by decoding the base64 version of the hash
