### ISSUE TITLE
Implement Focused Load Testing for Passport and Scorer API with k6

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1257]
**Goal:** Set up focused load testing for Passport and Scorer API using the k6 tool, with specific emphasis on our main usage scenarios. This will allow us to ensure the apps can handle the anticipated increase in traffic and maintain high performance as our user base grows.

**Tasks:**

- [x] **Ensure Staging Environment Mirrors Production:** Make sure the staging environment is a 1:1 replica of the production one in terms of sizing, CPU, memory, and DB. This is crucial for ensuring that our load testing results accurately reflect how our system will perform under load in the production environment.
- [x] **Define Main Usage Scenarios:** Define our main usage scenarios that we expect to occur frequently. These are likely to be a new user claiming an average of 10 stamps and getting their passport scored. We should consider both scenarios where scoring happens on the original page after a redirect and where scoring occurs directly in the Passport app.
- [x] **Set up k6 Tool and Create Load Test Scenarios:** Sign up for a k6 Cloud account and set up the tool based on our needs. Refer to the official k6 documentation and other online resources as needed. Then, create load test scenarios that reflect the main usage scenarios defined earlier.
- [x] **Run Load Tests:** Run these load tests against our staging environment. Make sure to take note of the results and performance metrics.
- [x] **Analyze Results and Improve Performance:** Use the results of the load tests to identify and address performance bottlenecks. We should continuously improve the performance of Passport and Scorer API based on the insights gained from the load testing.
- [x] **Documentation:** Document the process of setting up focused load testing, the test scenarios used, the results, and any performance improvements made. This will serve as a reference for future tests and for other teams wishing to set up similar load testing processes.

**Comment by nutrina** [comment]
@erichfi  in order to get this started here are my thoughts:

1. load testing will be done against our staging environment
2. we should make sure the staging environment is a 1:1 replica of the production one (same sizing / CPU / mem / DB)
3. we should outline what the expectation for a load scenario will be. For example, for the upcoming integrations, we will probably expect to have multiple users that will get a new passport and have that scores. So I think the scenario that will occur many times will be:
    a. a user goes to page guarded by Passport
    b. new users is redirected to Passport App
    b. the user claims on average 10 stamps
    c. the user goes back to the original page
    d. the user gets his passport scored

An alternative scneario would be if we score that users passport by default directly from the Passport app, as we did during the Beta round. This will shift some of the load in our API.

@erichfi  I think we should narrow down a bit the scope of this and making the expected outcome more focused

**Comment by nutrina** [comment]
HAve created 2 follow-up tickets to work on performance:
- #1330 
- #1325 
- #1329
