### ISSUE TITLE
Designing a New Score Credential for Gitcoin Passport's On-Chain System

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1303]
### Goal

We want to create a new type of credential that lives on the blockchain for Gitcoin Passport. This credential will hold a numeric score and the ID of who gave that score (scorer ID). We need to figure out how this credential will be structured and how to interpret it when it's stored on the blockchain.

### Tasks

- [x] **Plan the score credential:** We need to decide how to organize the score and scorer ID in the new credential. This is like designing a form where we need to decide what information goes where.
- [x] **Learn to interpret the score credential:** We need to work out how to understand what the score and scorer ID are when we look at the credential on the blockchain.
- [x] **Fit the new credential into our system:** We need to figure out how to add this new credential to our existing Ethereum Attestation Service based smart contract, which stores these credentials on the blockchain.

### Expected Outcomes

At the end of this SPIKE, we should:

1. Have a plan for the new score credential.
2. Know how to interpret the score credential when it's on the blockchain.
3. Understand how to add the new credential to our existing Ethereum Attestation Service based smart contract.

This will help us to move forward with adding this new score credential to the on-chain system of Gitcoin Passport.

**Comment by schultztimothy** [comment]
## Include the score and stamp data in one transaction

Suggested by @nutrina, we could have the iam server sign both the score and the stamp data

Adjustments to the `/eas` endpoint within iAM server:
- [ ] Make a request to the scorer api to get the score for the provided address
- [ ] Sign score using the EAS encoded representation of `{ score: number, scorer_id: bytes32, stamps: bytes32 }`
- [ ] Include both the signed stamp and score data in the response

Adjustments to Contract
- [ ] adjust signature verification to verify score data and score schema
- [ ] Adjust `function getMultiAttestRequest(` to return score schema and score attestation as part of the `MultiAttestationRequest`
- [ ] Make call to `attester.addPassport(getMultiAttestRequest(schema, passport));` with the combined data

**Comment by nutrina** [comment]
@schultztimothy another option for bringing multiple data structures on-chain would be to replace the function 
```sol
    function addPassportWithSignature(
        bytes32 schema,
        Passport calldata passport,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) public payable {
```

with a function like
```sol
`function multiAttest(uint8 v,
        bytes32 r,
        bytes32 s,
MultiAttestationRequest[] calldata multiRequests) external payable returns (bytes32[] memory);
```
 
This function would allow any data to be written to any schema, provided that the signature check passes and the EAS contract accepts the request.
In other words, we are open to write any data signed by the IAM to EAS in the future.

It comes however with a slight increase in gas fees as far as I can tell (probably due to the bigger calldata size ?).

**Comment by schultztimothy** [comment]
Yep this seems like the best option taking into account the schema changes we talked about this morning.
