### ISSUE TITLE
Integrate Passport Scorer Django App with Redash

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1350]
The aim of this chore is to establish a connection between our Passport Scorer Django application and Redash, allowing us to efficiently query our PostgreSQL database and create dynamic visualizations.

**Tasks:**

- [x] **Data Source Connection:** Set up a data source connection from Redash to our PostgreSQL database used by the Passport Scorer Django app. Ensure the correct settings (hostname, database name, user, password, etc.) are used for this connection.
- [x] **Data Validation:** Once the connection is set up, execute some test SQL queries to ensure that the data is correctly accessible via Redash.
- [x] **Initial Dashboard Setup:** Create an initial dashboard in Redash with some basic visualizations (e.g., total number of Passports, distribution of scores, etc.). This will be a proof of concept to demonstrate the successful integration.
- [x] **Documentation:** Document the steps taken during this integration, including the setup process, troubleshooting any issues, and how to create new queries and visualizations in Redash. This documentation will be valuable for any future developments.
- [x] **Knowledge Sharing:** Brief the team on how to use Redash for data exploration, visualization, and monitoring. Share the documentation created in the previous step.

**Acceptance Criteria:**

- A stable connection is established between Redash and our PostgreSQL database for the Passport Scorer Django app.
- Test SQL queries are successful and data is correctly reflected in Redash.
- An initial dashboard with basic visualizations is created in Redash.
- The integration process and usage instructions for Redash are well-documented.
- The team is briefed and understands how to use Redash for their tasks.

**Comment by schultztimothy** [comment]
@nutrina, @erichfi, or @zengatsu  I was going to start on this, but can't find the separate datasource we discussed in standup so that we can avoid making queries directly on our postgresdb. Do one of you know where that lives?

**Comment by schultztimothy** [comment]
We should now have a running instance of redash in our production aws instance. I wrote documentation on how it was spun up and debugging. https://www.notion.so/gitcoin/Passport-Redash-50af045eac3d4826987ccfc1902792e0

I'm still not able to connect to it from the browser, it looks like further ACL configuration is needed to expose it to the public.

**Comment by schultztimothy** [comment]
As discussed in engineering meeting, will need to create a read only user for the postgres instance. @nutrina will the still be necessary since we will be erading from the red replica?

**Comment by schultztimothy** [comment]
Dashboard has been created and queries will function better once https://github.com/gitcoinco/passport-scorer/pull/301 is rolled out

**Comment by schultztimothy** [comment]
Here is the link to the redash dashboard http://35.92.62.56:5000/dashboard/passport?p_Scorer%20Id=879

Here is the documentation on the instance as well https://www.notion.so/gitcoin/Passport-Redash-50af045eac3d4826987ccfc1902792e0 It is also located in the passport wiki
