### ISSUE TITLE
Load Testing for Upcoming November Traffic

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1769]
### Objective
To conduct load tests using the existing scenarios and to create and test a new scenario focusing on the IAM service, all within one workday.

### Background
With an expected surge in user traffic in November and the IAM service being a critical component, it's vital to understand how our system can handle increased activity.

### Tasks
- [x] Run Existing Load Test Scenarios: Use our current load test configuration to simulate high traffic. Timebox: 1.5 hours
- [x] Develop a New Load Test Scenario for IAM: Create a realistic usage scenario specifically targeting the IAM service. Timebox: 2 hours
- [x] Conduct the IAM Load Test: Perform the load test with the newly created IAM scenario. Timebox: 1.5 hours
- [x] Collect and Analyze Data: Capture performance data, bottlenecks, etc., after running the tests. Timebox: 2 hours
- [x] Report Findings: Summarize the findings and outline recommended actions and next steps. Timebox: 1 hour

### Acceptance Criteria

- Existing load test scenarios are run successfully and results are documented.
- A new load test scenario focusing on the IAM service is created and executed.
- A report is generated that includes findings, recommended actions, and next steps.

#### Open Questions

- Which IAM interactions do we expect to be the most heavily utilized in November?
- Is there prior data to compare the new load test results to?

#### Timebox
This SPIKE is timeboxed to one workday.

**Comment by lucianHymer** [comment]
We should wait for https://github.com/gitcoinco/passport-scorer/issues/434 and https://github.com/gitcoinco/passport/issues/1790 to be on staging before doing this testing

**Comment by lucianHymer** [comment]
Analysis:

RDS Proxy vs Direct DB Connection:
- Proxy is slightly slower (~13% slower)
- Error rate is 30% lower for proxy


Lambdas vs ECS
- Lambda is 20% faster on average once scaled, even with additional score calcs
- Lambda max is roughly 3x faster once scaled (15s vs 45s)
- Lambda has no timeout errors after first 12 minutes (once scaled)
- Lambda average scales very quickly, most users won't notice anything


IAM Load Tests
- Identified very easy fix that took us from 33% to 0% error rate under load (setting keepalive timeout on the express server)
- We can cut the IAM back to 1vCPU and autoscale at 50% and still get a 0% error rate and smooth scaling
- The node instance is super robust, but average times will grow as load grows. Using more, smaller instances scales to a lower average response times. But <1vCPU per instance results in some timeout errors

**Comment by lucianHymer** [comment]
Test results: https://drive.google.com/file/d/1_26yX5P7cg-rGfSZp70-Ae3l_aAoyBCT/view?usp=drive_link
