### ISSUE TITLE
Finalize and Deploy the Decoder and Dependencies to Optimism and Linea Mainnets

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1986]
**Related to:** Continuation of Chore #1928

### Description:
This chore entails completing the development of the decoder and its dependencies, ensuring they are ready for deployment to both the Optimism and Linea mainnets. Key tasks include:

- [x] **Implement Review Suggestions:** Thoroughly review and incorporate the suggestions from the latest code review. Each suggestion must be evaluated and, where applicable, integrated to improve the decoder's quality and functionality.
- [x] **Resolve TODOs in Code:** Identify and resolve all 'TODO' annotations in the code. This is a critical step to ensure the code is fully completed and deployment-ready, leaving no pending tasks or placeholders.
- [x] **Script for Setting Bitmap:** Develop a script that effectively sets the bitmap, a crucial component for the decoder's proper functionality in the operational environment.
- [x] **Comprehensive Testnet Deployment:** Ensure the deployment of the Onchain Passport to all currently supported testnets, including but not limited to OP Sepolia. This task must confirm the compatibility of the Onchain Passport with each supported testnet, focusing particularly on ensuring smooth functionality on both Optimism and Linea networks.
- [ ] **Update Deployment Documentation for Network Integration:** Draft and integrate a new section into the deployment documentation, specifically detailing the process of including the decoder in any network deployment. This task involves outlining the necessary steps and considerations for ensuring the decoder is consistently and effectively deployed as part of any network rollouts, thereby standardizing its integration across different environments.
----
**Update**
- [ ] make sure script to check for missing on-chain providers is part of the CI
- [ ] throw an error in case the user is trying to write an attestation on-chain that is not yet included in the provider bitmap

### Action Plan:

- Start by addressing the review suggestions, systematically working through each point.
- Progress to resolving all TODOs in the code to ensure its robustness and readiness for deployment.
- Create the bitmap setting script, making sure it meets the requirements and integrates seamlessly with the existing system.
- Regularly update this chore with progress reports and any challenges encountered.

### Collaboration:
**Attention:** Coordinate with @nutrina prior to starting this task. Pairing with @nutrina is essential for gaining insights and aligning with the project's overall goals and standards.

### Notes:

- Successful completion of this chore is vital for the deployment phase. Meticulous attention to detail in each step is crucial.
- Maintain documentation of all changes and updates for team reference and future maintenance, with a specific focus on compatibility with both the Optimism and Linea mainnets.

**Comment by nutrina** [comment]
See the checklist for the deployment here:

https://github.com/gitcoinco/passport/issues/1928#issuecomment-1881080049

**Comment by digitalmnt** [comment]
Moving this back to prioritized until someone can pair with @nutrina, it seems like most if not all of this is complete

**Comment by digitalmnt** [comment]
One other note is that openzeppelin released breaking changes to their Upgrades contracts and the linked pr begins implementing those new contracts

**Comment by digitalmnt** [comment]
I talked with @nutrina this morning and we are planning to pair on Monday morning to deploy these updates. Everything should be in a good spot.

**Comment by digitalmnt** [comment]
Current state of things:

OP: 
GitcoinResolver - updated implementation has been deployed to 0xC2687F3E1A9A0eDcF132ef9B6EdcEA254DF1C5C8 and a transaction has been created within the multsig to point the Resolver proxy to the new implementation

GitcoinAttester - Waiting on somone to initiate the upgrade from the gitcoinmultisig
✅ Deployed Upgraded GitcoinAttester 0x423cd60ab053F1b63D6F78c8c0c63e20F009d669
✅ Updated ./deployments/abi/GitcoinAttester.json
✏️ You should copy the ./deployments directory to the Passport frontend, overwriting the current one
Upgrade transaction data: 0x3659cfe6000000000000000000000000423cd60ab053f1b63d6f78c8c0c63e20f009d669
GitcoinPassportDecoder - Has been deployed here https://optimistic.etherscan.io/address/0x5558D441779Eca04A329BcD6b47830D2C6607769 we need to wait for the GitcoinResolver to be updated before the contract is functional

GitcoinVerifier - Small update was made since the last deployment, allow withdrawing a specific amount from the contract as opposed to the whole amount. Gas prices are somewhat high right now and @nutrina suggested waiting to deploy this update

**Comment by digitalmnt** [comment]
Here are the Linea deployments with upgrade data for the multisig

Linea Decoder:

Set GitcoinResolver address 0x0a774AECE542a1A819107Eb3a06E9D515C67257a on GitcoinPassportDecoder.
✅ Set Passport SchemaUID to 0x69b9d63ff6b161097cb4930e197a722bcf423f832d4e4cd3692449d5a1e1319f on GitcoinPassportDecoder.
✅ Set Passport SchemaUID to 0x4da1eaac6346b8b79a705e3898a308062ca607f56c07762ef7b7ff8a7661843c on GitcoinPassportDecoder.
✅ Set maxScoreAge to 7776000 on GitcoinPassportDecoder.
✅ Set threshold to 200000 on GitcoinPassportDecoder.
currentVersion 0n
providers: [
'SelfStakingBronze',
'SelfStakingSilver',
'SelfStakingGold',
'CommunityStakingBronze',
'CommunityStakingSilver',
'CommunityStakingGold',...

Linea GitcoinResolver
┌──────────┬───────────────────┐
│ (index) │ Values │
├──────────┼───────────────────┤
│ contract │ 'GitcoinResolver' │
│ network │ 'linea' │
│ chainId │ 59144 │
└──────────┴───────────────────┘

Do you want to continue? y/N
y

(node:14391) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
✅ Deployed Upgraded GitcoinResolver. 0xdf5cECD9D8f17366023ecc011Ac8130b94524eBA
✅ Updated ./deployments/abi/GitcoinResolver.json
✏️ You should copy the ./deployments directory to the Passport frontend, overwriting the current one
Upgrade transaction data: 0x3659cfe6000000000000000000000000df5cecd9d8f17366023ecc011ac8130b94524eba

Resolver 'setScoreSchema' transaction data: 0xc927ee374da1eaac6346b8b79a705e3898a308062ca607f56c07762ef7b7ff8a7661843c

It should already have an allow list since changes were for Verax

Debugger attached.

PARAMETERS
┌──────────┬───────────────────┐
│ (index) │ Values │
├──────────┼───────────────────┤
│ contract │ 'GitcoinAttester' │
│ network │ 'linea' │
│ chainId │ 59144 │
└──────────┴───────────────────┘

Do you want to continue? y/N
y

(node:15001) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
✅ Deployed Upgraded GitcoinAttester 0x8a0d8Fb8C26e972090382AE6965Cc839fee6c1A5
✅ Updated ./deployments/abi/GitcoinAttester.json
✏️ You should copy the ./deployments directory to the Passport frontend, overwriting the current one
Upgrade transaction data: 0x3659cfe60000000000000000000000008a0d8fb8c26e972090382ae6965cc839fee6c1a5

**Comment by nutrina** [comment]
Waiting for final signature and execution of transaction to test.

**Comment by nutrina** [comment]
Waiting for another signature + execution

**Comment by nutrina** [comment]
This is now deployed. Have tested it and it works.
