### ISSUE TITLE
Infra Week #3

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2772]
### Infra Weeks Roadmap Overview

- [ ] Update dependencies in the Passport app and resolve build issues with the latest libraries
  - Issue: [GitHub #2889](https://github.com/passportxyz/passport/issues/2889)
- [ ] Troubleshoot instance issues
  - Assigned: @Larisa : https://github.com/passportxyz/core-infra/issues/57
- [ ] drop awsx in pulumi: https://github.com/passportxyz/core-infra/issues/39
- [ ] Fix shuffling of environment variables & secrets within Pulumi 
  - Issue: [GitHub #2890](https://github.com/passportxyz/passport/issues/2890)
- [ ] Use private endpoints for internal stuff
  - Issue https://github.com/passportxyz/core-infra/issues/35
- [ ] Switch to Aurora Serverless : this should not be completed now until we clarify if we can drop the current reservations 
  - [ ]  @larisa17  to create issue
- [ ] Adjust alarms (we have many false alarms, check PD and adjust alarms monitoring parameters): https://github.com/passportxyz/core-infra/issues/64
- [ ] consolidate all Alchemy RPC urls
  - [ ] https://github.com/passportxyz/passport/issues/2989
- [ ] remove old secrets from 1P:
  - [x] https://github.com/passportxyz/core-infra/issues/65
- [ ] ensure proper creation of releases in GH when running the release workflow
  - [x] https://github.com/passportxyz/passport/issues/2990
- [ ] upgrade RDS version
  - [x] https://github.com/passportxyz/core-infra/issues/60

 ⬆ Issues are prioritised above this line ⬆

- [ ] Implement a user-friendly solution to track the status/progress of backfill/rescore commands
  - TODO: @nutrina to link to the concept design
- [ ] Address duplicate Stamps within the same Passport
  - Confirmation needed: @lucianHymer
- [ ] Resolve release notes generation issue (currently failing on Scorer)
  - Issue: [GitHub #2838](https://github.com/passportxyz/passport/issues/2838)
- [ ] Conduct cost exploration
  - Verification needed: @larisa17 - Is this already covered?
  - Ensure proper resource tagging
- [ ] Integrate linter for JS/TS code 
  - Issue: [GitHub #2891](https://github.com/passportxyz/passport/issues/2891)
- [ ] Transition `passport-scorer` to utilize the SNS topic from core-infra
  - Issue: [GitHub #2892](https://github.com/passportxyz/passport/issues/2892)
- [ ] Establish proper `.env` and `README` in `passport-scorer/indexer`
- [ ] Update environment variables to uppercase in the `Passport-Data-Science` repo
- [ ] Align infra in the `Passport-Data-Science` repo with guidelines from `passport` and `passport-scorer`
- [ ] Migrate the `data-models` database to the core infra
- [ ] Can we stick to a convention for the postgres db connection strings? We should use this dialect: `postgresql://...`. In the data science repo we need to change the dialect, see: https://github.com/passportxyz/Passport-Data-Science/pull/231/files#diff-5c79e92c8608287fe84d7d6e7fc3644db1eafa39644e981a71cb5c9026a4cea5R16-R26
- [ ] Review & move this to the infra libs: https://github.com/passportxyz/Passport-Data-Science/blob/2788-basic-slashing-analysis/infra/lib/ecs/scheduled_tasks.ts
- [ ] use internal VPC endpoints (cost savings): https://github.com/passportxyz/core-infra/issues/35
- [ ] alert for CPU & memory usage for the DB: https://github.com/passportxyz/core-infra/issues/44
- [ ] uptime robot to generate & write  unique stamps: https://github.com/passportxyz/passport/issues/2778
- [ ] upgrade postgres DB engine version in RDS:  https://github.com/passportxyz/core-infra/issues/60

**Comment by larisa17** [comment]
For cost exploration there is nothing much we can do now: we just added the required tags to see how the costs are distributed. We have a ticket to add some adjustments to CloudFront which should reduce the costs. @nutrina  should we still consider moving to AWS aurora to reduce the costs generated by RDS ? 

Troubleshooting instance : 
- all required tools (aws, docker, psql ) should be already installed and available to the current user (ubuntu , executing commands via sudo should not longer be required )
- remove the old scorer troubleshooting instance 
- adjust the setup of ec2 instance to be able to pull docker images from private repositories without running AWS ecr login command every time 
- setup a script to have it available to read the RDS connection details from the AWS Secrets Manager and do a docker run on the last passport scorer ECR image pushed. This is required to easily run migrations during the release & remove the db credentials from the pulumi output (which is a security breach)

**Comment by larisa17** [comment]
I would also like to complete the setup of 1Password secrets : adjust the tags &  setup a cli command to have the environment variables (.env file) completed from 1Password for local development

**Comment by larisa17** [comment]
Possible tickets: 
- https://github.com/passportxyz/core-infra/issues/35 
- https://github.com/passportxyz/core-infra/issues/44 
- https://github.com/passportxyz/core-infra/issues/46
