### ISSUE TITLE
2nd Scoring Mechanism

### ISSUE THREAD

**Issue by Etovardesign** [gitcoinco/passport#996]
**Tasks**

- [ ] Review Consider & Explore Brief
- [ ] [Identify Problems & Proposed Solutions](https://miro.com/app/board/uXjVPwehjfI=/?moveToWidget=3458764546832380790&cot=14)
- [ ] Define Research Plan
- [ ] [Generate Research Questions](https://docs.google.com/document/d/1sUXO5H3pFZgW2IqtbxTpnOj6lNgu1rD05UcNUXIyXhc/edit?usp=sharing)
- [ ] Schedule Interviews
